name: Build and deploy Node.js project to Azure Function App - az-products-orchestrator

on:
  push:
    branches:
      - main
    paths:
      - 'productorchestrator/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install and build'
        run: |
          npm install
          # npm run build
          # npm prune --production

      - name: 'display all files'
        run: |
          Get-ChildItem ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        shell: pwsh

      - name: 'Create ZIP'
        run: |
          Get-ChildItem ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} | Compress-Archive -Destination .\backend.zip
        shell: pwsh

      - name: 'display all files after zip'
        run: |
          Get-ChildItem ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        shell: pwsh

      - name: 'Deploy the ZIP to the app'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'az-products-orchestrator'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_Product_Orchestrator }}
          package: ./backend.zip
