name: Build and deploy Node.js project to Azure Function App - az-products-orchestrator

on:
  push:
    branches:
      - main
    paths:
      - 'productorchestrator/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: productorchestrator

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'print contents '
        shell: bash
        run: |
          ls -lrt .

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd '.'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      # - name: 'Run Azure Functions Action'
      #   uses: Azure/functions-action@v1
      #   id: fa
      #   with:
      #     app-name: 'az-products-orchestrator'
      #     slot-name: 'production'
      #     package: .
      #     publish-profile: ${{ secrets.AzureAppService_PublishProfile_Product_Orchestrator }}
      - name: 'Create ZIP'
        run: |
          Get-ChildItem . | Compress-Archive -Destination .\backend.zip
        shell: pwsh
      - name: 'print contents post zip'
        shell: bash
        run: |
          ls -lrt .

      - name: 'Deploy the ZIP to the app'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'az-products-orchestrator'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_Product_Orchestrator }}
          package: backend.zip
