name: Build and deploy Nodejs app to az functions

on:
  push:
    branches:
      - main
    paths:
      - 'productorchestrator/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: productorchestrator

env:
  AZURE_FUNCTION_PROJ_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)
  AZURE_FUNCTIONAPP_NAME: 'product-details-orchestrator'
  FUNCTIONS_WORKER_RUNTIME: 'node'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'print contents '
        shell: bash
        run: |
          ls -lrt .

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd '.'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: Authenticate to Azure as a Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS_FUNCTION_APP }}

      - name: Install Azure Functions Core Tools
        run: npm i -g azure-functions-core-tools@3 --unsafe-perm true

      - name: Publish Azure Function App
        run: func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }}
